import Foundation

public enum CreateShieldInformationBarrierSegmentRestrictionRequestBodyArgShieldInformationBarrierSegmentFieldTypeField: String, CodableStringEnum {
    case shieldInformationBarrierSegment = "shield_information_barrier_segment"
}
